apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "debezium-service.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  DEPLOY_MODE: KUBERNETES_ONPREM
  MEMORY: {{ .Values.java.memory | quote }}
  STACK_DRIVER_LOGGING_ENABLED: {{ .Values.global.stackDriverLoggingEnabled | quote }}
  EVENTS_FRAMEWORK_REDIS_URL: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  EVENTS_FRAMEWORK_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME: 'harness-redis'
  EVENTS_FRAMEWORK_REDIS_SENTINELS: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
#  EVENTS_FRAMEWORK_ENV_NAMESPACE: {{.Values.EVENTS_FRAMEWORK_ENV_NAMESPACE}}
#  EVENTS_FRAMEWORK_REDIS_SSL_ENABLED: {{.Values.EVENTS_FRAMEWORK_REDIS_SSL_ENABLED | quote}}
#  EVENTS_FRAMEWORK_REDIS_SSL_CA_TRUST_STORE_PATH: {{.Values.EVENTS_FRAMEWORK_REDIS_SSL_CA_TRUST_STORE_PATH}}
#  EVENTS_FRAMEWORK_REDIS_SSL_CA_TRUST_STORE_PASSWORD: {{.Values.EVENTS_FRAMEWORK_REDIS_SSL_CA_TRUST_STORE_PASSWORD  | quote}}
  REDIS_LOCK_CONFIG_REDIS_SENTINELS: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
  REDIS_LOCK_CONFIG_SENTINEL_MASTER_NAME: harness-redis
  REDIS_LOCK_CONFIG_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  REDIS_LOCK_CONFIG_REDIS_URL: {{ include "harnesscommon.dbconnectionv2.redisConnection" (dict "context" $) }}
#  REDIS_LOCK_CONFIG_ENV_NAMESPACE: {{.Values.REDIS_LOCK_CONFIG_ENV_NAMESPACE | quote}}
  IS_ENABLED_PIPELINE: {{.Values.config.IS_ENABLED_PIPELINE | quote}}
  MONGO_DB_SSL_ENABLED_PIPELINE: {{.Values.config.MONGO_DB_SSL_ENABLED_PIPELINE | quote}}
  COLLECTION_INCLUDE_LIST_PIPELINE: {{.Values.config.COLLECTION_INCLUDE_LIST_PIPELINE | quote}}
  DEBEZIUM_NAME_PIPELINE: {{.Values.config.DEBEZIUM_NAME_PIPELINE | quote}}
  MONGODB_NAME_PIPELINE: {{.Values.config.MONGODB_NAME_PIPELINE | quote}}
  DATABASE_INCLUDE_LIST_PIPELINE: {{.Values.config.DATABASE_INCLUDE_LIST_PIPELINE | quote}}
  REDIS_STREAM_SIZE_PIPELINE: {{.Values.config.REDIS_STREAM_SIZE_PIPELINE | quote}}
  SNAPSHOT_MODE_PIPELINE: {{.Values.config.SNAPSHOT_MODE_PIPELINE | quote}}
  MAX_QUEUE_SIZE_PIPELINE: {{.Values.config.MAX_QUEUE_SIZE_PIPELINE | quote}}
  MAX_BATCH_SIZE_PIPELINE: {{.Values.config.MAX_BATCH_SIZE_PIPELINE | quote}}
  MAX_QUEUE_SIZE_IN_BYTES_PIPELINE: {{.Values.config.MAX_QUEUE_SIZE_IN_BYTES_PIPELINE | quote}}
  POLL_INTERVAL_MS_PIPELINE: {{.Values.config.POLL_INTERVAL_MS_PIPELINE | quote}}
  FIELD_EXCLUDE_LIST_PIPELINE: {{.Values.config.FIELD_EXCLUDE_LIST_PIPELINE | quote}}
#  MONGODB_CONNECTION_STRING_PIPELINE: {{.Values.config.MONGODB_CONNECTION_STRING_PIPELINE | quote}}
  LIST_OF_ERROR_CODES_FOR_OFFSET_RESET: {{.Values.config.LIST_OF_ERROR_CODES_FOR_OFFSET_RESET | quote}}

  IS_ENABLED_APPLICATIONS: {{.Values.config.IS_ENABLED_APPLICATIONS | quote}}
  MONGODB_SSL_ENABLED_APPLICATIONS: {{.Values.config.MONGODB_SSL_ENABLED_APPLICATIONS | quote}}
  COLLECTION_INCLUDE_LIST_APPLICATIONS: {{.Values.config.COLLECTION_INCLUDE_LIST_APPLICATIONS | quote}}
  DEBEZIUM_NAME_APPLICATIONS: {{.Values.config.DEBEZIUM_NAME_APPLICATIONS | quote}}
  MONGODB_NAME_APPLICATIONS: {{.Values.config.MONGODB_NAME_APPLICATIONS | quote}}
  DATABASE_INCLUDE_LIST_APPLICATIONS: {{.Values.config.DATABASE_INCLUDE_LIST_APPLICATIONS | quote}}
  REDIS_STREAM_SIZE_APPLICATIONS: {{.Values.config.REDIS_STREAM_SIZE_APPLICATIONS | quote}}
  SNAPSHOT_MODE_APPLICATIONS: {{.Values.config.SNAPSHOT_MODE_APPLICATIONS | quote}}
  MAX_QUEUE_SIZE_APPLICATIONS: {{.Values.config.MAX_QUEUE_SIZE_APPLICATIONS | quote}}
  MAX_BATCH_SIZE_APPLICATIONS: {{.Values.config.MAX_BATCH_SIZE_APPLICATIONS | quote}}
  MAX_QUEUE_SIZE_IN_BYTES_APPLICATIONS: {{.Values.config.MAX_QUEUE_SIZE_IN_BYTES_APPLICATIONS | quote}}
  POLL_INTERVAL_MS_APPLICATIONS: {{.Values.config.POLL_INTERVAL_MS_APPLICATIONS | quote}}
  FIELD_EXCLUDE_LIST_APPLICATIONS: {{.Values.config.FIELD_EXCLUDE_LIST_APPLICATIONS | quote}}
#  MONGODB_CONNECTION_STRING_APPLICATIONS: {{.Values.config.MONGODB_CONNECTION_STRING_APPLICATIONS | quote}}

  SNAPSHOT_EVENTS_FRAMEWORK_REDIS_URL: {{.Values.config.SNAPSHOT_EVENTS_FRAMEWORK_REDIS_URL | quote}}
  SNAPSHOT_EVENTS_FRAMEWORK_ENV_NAMESPACE: {{.Values.config.SNAPSHOT_EVENTS_FRAMEWORK_ENV_NAMESPACE | quote}}
  IS_ENABLED_PIPELINE_SNAPSHOT: {{.Values.config.IS_ENABLED_PIPELINE_SNAPSHOT | quote}}
  MONGODB_SSL_ENABLED_PIPELINE_SNAPSHOT: {{.Values.config.MONGODB_SSL_ENABLED_PIPELINE_SNAPSHOT | quote}}
  DATABASE_INCLUDE_LIST_PIPELINE_SNAPSHOT: {{.Values.config.DATABASE_INCLUDE_LIST_PIPELINE_SNAPSHOT | quote}}
  COLLECTION_INCLUDE_LIST_PIPELINE_SNAPSHOT: {{.Values.config.COLLECTION_INCLUDE_LIST_PIPELINE_SNAPSHOT | quote}}
  REDIS_STREAM_SIZE_PIPELINE_SNAPSHOT: {{.Values.config.REDIS_STREAM_SIZE_PIPELINE_SNAPSHOT | quote}}
  FIELD_EXCLUDE_LIST_PIPELINE_SNAPSHOT: {{.Values.config.FIELD_EXCLUDE_LIST_PIPELINE_SNAPSHOT | quote}}
#  MONGODB_CONNECTION_STRING_PIPELINE_SNAPSHOT: {{.Values.config.MONGODB_CONNECTION_STRING_PIPELINE_SNAPSHOT | quote}}

  IS_ENABLED_PLG: {{.Values.config.IS_ENABLED_PLG | quote}}
  MONGODB_SSL_ENABLED_PLG: {{.Values.config.MONGODB_SSL_ENABLED_PLG | quote}}
  COLLECTION_INCLUDE_LIST_PLG: {{.Values.config.COLLECTION_INCLUDE_LIST_PLG | quote}}
  DEBEZIUM_NAME_PLG: {{.Values.config.DEBEZIUM_NAME_PLG | quote}}
  MONGODB_NAME_PLG: {{.Values.config.MONGODB_NAME_PLG | quote}}
  DATABASE_INCLUDE_LIST_PLG: {{.Values.config.DATABASE_INCLUDE_LIST_PLG | quote}}
  REDIS_STREAM_SIZE_PLG: {{.Values.config.REDIS_STREAM_SIZE_PLG | quote}}
  SNAPSHOT_MODE_PLG: {{.Values.config.SNAPSHOT_MODE_PLG | quote}}
  MAX_QUEUE_SIZE_PLG: {{.Values.config.MAX_QUEUE_SIZE_PLG | quote}}
  MAX_BATCH_SIZE_PLG: {{.Values.config.MAX_BATCH_SIZE_PLG | quote}}
  MAX_QUEUE_SIZE_IN_BYTES_PLG: {{.Values.config.MAX_QUEUE_SIZE_IN_BYTES_PLG | quote}}
  POLL_INTERVAL_MS_PLG: {{.Values.config.POLL_INTERVAL_MS_PLG | quote}}
#  MONGODB_CONNECTION_STRING_PLG: {{.Values.config.MONGODB_CONNECTION_STRING_PLG | quote}}

  IS_ENABLED_SSCA: {{.Values.global.ssca.enabled | quote}}
  MONGODB_SSL_ENABLED_SSCA: {{.Values.config.MONGODB_SSL_ENABLED_SSCA | quote}}
  COLLECTION_INCLUDE_LIST_SSCA: {{.Values.config.COLLECTION_INCLUDE_LIST_SSCA | quote}}
  DEBEZIUM_NAME_SSCA: {{.Values.config.DEBEZIUM_NAME_SSCA | quote}}
  MONGODB_NAME_SSCA: {{.Values.config.MONGODB_NAME_SSCA | quote}}
  DATABASE_INCLUDE_LIST_SSCA: {{.Values.config.DATABASE_INCLUDE_LIST_SSCA | quote}}
  REDIS_STREAM_SIZE_SSCA: {{.Values.config.REDIS_STREAM_SIZE_SSCA | quote}}
  SNAPSHOT_MODE_SSCA: {{.Values.config.SNAPSHOT_MODE_SSCA | quote}}
  MAX_QUEUE_SIZE_SSCA: {{.Values.config.MAX_QUEUE_SIZE_SSCA | quote}}
  MAX_BATCH_SIZE_SSCA: {{.Values.config.MAX_BATCH_SIZE_SSCA | quote}}
  MAX_QUEUE_SIZE_IN_BYTES_SSCA: {{.Values.config.MAX_QUEUE_SIZE_IN_BYTES_SSCA | quote}}
  POLL_INTERVAL_MS_SSCA: {{.Values.config.POLL_INTERVAL_MS_SSCA | quote}}
#  MONGODB_CONNECTION_STRING_SSCA: {{.Values.config.MONGODB_CONNECTION_STRING_SSCA | quote}}
  {{ include "harnesscommon.harnessfunctions.java17flags" (dict "context" $) | nindent 2 }}
  # Additional configs
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
  {{- include "harnesscommon.monitoring.config" . | nindent 2 }}