apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debezium-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "debezium-service.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
